name: utilities

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                node-version: "22.x"
                cache: 'pnpm'

            - run: pnpm install
            - run: pnpm run e2e:install
            - run: pnpm run build
            - run: pnpm run format:check
            - run: pnpm run lint
            - run: pnpm run unit

            - uses: actions/upload-artifact@v4
              with:
                  name: utilities
                  path: build/
